config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Voir tout les tasks
  get '/tasks', to: 'tasks#index'
  # Créer un task
  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'
  # Voir le détail d'un task
  get '/tasks/:id', to: 'tasks#show', as: :task
  # Modifier un task
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch '/tasks/:id', to: 'tasks#update'
  # Supprimer un task
  delete '/task/:id', to: 'tasks#destroy', as: :task_delete
  # resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    # On récupère tout les tasks
    @tasks = Task.all
  end

  def show
    # On récupère 1 seul task
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params_task)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(params_task)
    @task.save
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  private

  def params_task
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f|%>
  <div class = "letter">
    <div class = "letter1">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class = "letter1">
      <%= f.label :details %>
      <%= f.text_field :details %>
    </div>
    <div class = "letter1">
      <%= f.label :completed %>
      <%= f.number_field :completed %>
    </div>
    <%= f.submit class:"a"%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>NEW TASKS</h1>
<ol>
  <% @tasks.each do |task| %>
    <li> <%= link_to task.title, task_path(task) %> </li>
  <% end %>
</ol>

<%= link_to "Create New task", tasks_new_path(@task), class: "a" %>

app/views/tasks/new.html.erb
<br>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div>
<div  class= "h1">
<h1> <%= @task.title %> </h1>
</div>
<div  class= "h1">
<p> <%= @task.details %> </p>
</div>
<div  class= "h1">
<p> <%= @task.completed %></p>
</div>
</div>

<div>
<div class = "a">
<%= link_to "Delete task", task_delete_path(@task), method: :delete, data: { confirm: "Are you sure ?"} %>
</div>
<div class = "a">
<%= link_to "Update task", edit_task_path(@task) %>
</div>
<div class = "a">
<%= link_to "Back", tasks_path %>
</div>
</div>